version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  gamelobby:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gamelobby
    depends_on:
      - redis
    ports:
      - "5144:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Redis__ConnectionString=redis:6379,abortConnect=false,connectRetry=3,connectTimeout=5000
