apiVersion: v1
kind: Service
metadata:
  name: gamelobby
  namespace: game
spec:
  selector: { app: gamelobby }
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamelobby
  namespace: game
spec:
  replicas: 3 
  selector:
    matchLabels: { app: gamelobby }
  template:
    metadata:
      labels: { app: gamelobby }
    spec:
      containers:
        - name: gamelobby
          image: gamelobby:local
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: Redis__ConnectionString         # => Redis:ConnectionString
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: REDIS__CONNECTIONSTRING
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: "/health", port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/health", port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20
